name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"
  sonar_project: "ConnectFourGithub"
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build:
    runs-on: self-hosted
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'adopt'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn compile

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test
        run: mvn test

  analyze:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile
        run: mvn compile

      - name: Analyze
        run: mvn sonar:sonar -Dsonar.projectKey=$sonar_project -Dsonar.qualitygate.wait=true

  package:
    needs: analyze
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ConnectFour.war
          path: target/ConnectFour.war

  deploy:
    needs: package
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ConnectFour.war
          path: target

      - name: Deploy
        run: |
          sudo docker rm -f tomcat
          sudo docker image rm -f connect-four
          sudo docker build -t connect-four .